### ISSUE TITLE
Update install documentation/make process

### ISSUE THREAD

**Issue by GerbertBless** [airvzxf/bose-connect-app-linux#4]
Hey there,

I don't know much about programing in C or how make works and am using this as an opportunity to learn as I really want to use all the features of my sport open earbuds. Forgive me if anything I am about to write comes from a misunderstanding.

It looks like you more or less copied the installation instructions from the original based-connect project, however, while these instructions worked for that project, they do not see to work for this one. 

The directory structure of this project is quite different and I see no Makefile. The instructions did not work for me, however, I was able to create an executable by blindly fooling around with cmake. It is not installed as I have to run it as an executable directly from the project directory.

I'm unsure if maybe you've worked on this through an IDE and haven't been checking the CLI side of things or if I'm totally misunderstanding something, but I imagine you'd want to update either the documentation or the make process. I'm going to try to learn more about this stuff so I can see how I might can help in the future.

Quick aside: I'll be testing my open-ear sports earbuds with this when I get the chance and confirm whether it is working with them or not.

**Comment by airvzxf** [comment]
Thank you and don't worry. I like the direct feedback, and yours is good to improve this project.

Yes, I'm working with CLion IDE and I didn't test directly in the command. I'll try, and I'll update the main branch.

The CMake installation is not working or tested because I was focus on the quality code right now. I added into the To-Do's list (https://github.com/airvzxf/bose-connect-app-linux/blob/main/TODO.md). I'll update the READ ME file.

Please notify me if your open-ear sports, work with this project.

**Comment by airvzxf** [comment]
Hi, again.

I committed significant changes in the pull request #6. I updated the [read me file][read-me-build], please check and test.

Could you check if it works for you? The changes are on the [main branch][main-branch]. I wonder if you are using Ubuntu or Arch Linux because it should be crash on Ubuntu, but I need someone to test, and you could be this man. Just in case it fails, could we have a Google meeting to check the problems and try to fix quickly?

_If this issue is not responded in two or three weeks, it will close._

[main-branch]: https://github.com/airvzxf/bose-connect-app-linux

[read-me-build]: https://github.com/airvzxf/bose-connect-app-linux/tree/quality-assurance-code#build-and-installation

**Comment by GerbertBless** [comment]
Hello! 

Sorry it took so long to get back to you. I kind of left and went off the grid for a little bit. I'm running Arch Linux from my laptop. I took a look at everything and the bash scripts build and install the software perfectly. I am definitely open to helping you test Ubuntu as I have a mint machine as well as a few running variants of Debian.

Still haven't gotten around to testing with my earbuds and can't right now because they are dead. In all honesty, I have yet to even get any sound to come out of them with my laptop and haven't tried it on other Linux computers, even though other Bluetooth devices seem to work fine with my laptop. I am unsure if this is because I may have configured my Bluetooth incorrectly, as this is my first Arch install, (I'm learning i3, trying out minimalist alternatives to things, etc, and am still in the process of configuring it how I would like even if it is currently functional for most uses. I'll let you know when I can definitely see if it works. Going to try it with a live usb later.

**Comment by airvzxf** [comment]
That sounds good, at least it installs perfectly. Sorry about your earbuds 😕.

I created a repository with all the scripts for the installation process of Arch Linux in my Laptops. If you want to look, maybe it helps you in some specific subject. It is the latest updated laptop:  [laptop_MSI_GT73EVR_7R_Titan_Pro](https://github.com/airvzxf/archLinux-installer-and-setup/tree/master/src/laptop_MSI_GT73EVR_7R_Titan_Pro).

In the file [99i-linux-commands.sh](https://github.com/airvzxf/archLinux-installer-and-setup/blob/master/src/laptop_MSI_GT73EVR_7R_Titan_Pro/05-knowledge/99i-linux-commands.sh), I have many commands for some setup or run something. The code below contains the section with the Bluetooth audio:

```bash
# Connect bluetooth headset
# https://purplepalmdash.github.io/2013/12/19/bluetooth-headset-on-archlinux/
# https://wiki.archlinux.org/index.php/Bluetooth_headset#Headset_via_Bluez5.2FPulseAudio
sudo pacman -S --needed --noconfirm pulseaudio-alsa
sudo pacman -S --needed --noconfirm pulseaudio-bluetooth
sudo pacman -S --needed --noconfirm bluez
sudo pacman -S --needed --noconfirm bluez-libs
sudo pacman -S --needed --noconfirm bluez-utils

# This package not work properly in my laptop.
# yay -S bluez-utils-compat
# gpg --recv-keys 06CA9F5D1DCF2659


# How to check if you missing some module
lsmod > loaded-modules-before-sleep.txt
# Sleep your computer and wake up.
lsmod > loaded-modules-after-sleep.txt
diff loaded-modules-before-sleep.txt loaded-modules-after-sleep.txt


# Bluetooth problems when can't turn on the power or anothers
# https://unix.stackexchange.com/questions/113828/how-to-find-and-reload-specific-driver-from-kernel
lsmod | grep -i bluetooth
# bluetooth: 10 btrtl,btintel,bnep,btbcm,rfcomm,ath3k,btusb
sudo rmmod ath3k && sudo modprobe ath3k
sudo rmmod btusb && sudo modprobe btusb
# Sleep the computer.
sudo systemctl restart bluetooth
bluetoothctl
# Wait until the controller is loaded again.


# Run these the first time
# Make sure your device is not blocked
rfkill list
#sudo rfkill unblock all
modprobe btusb
systemctl start bluetooth.service
pulseaudio -k

# Turn on your headset device

# Set up the first time
bluetoothctl
# Enter the next commands
# $ power on
# $ agent on
# $ default-agent
# $ scan on
# It shows:
#    [NEW] Device 30:23:57:A2:71:59 BX950
# $ trust [MAC Address]
# $ pair [MAC Address]
# $ connect [MAC Address]
# $ scan off
# $ exit

# If you had setted up your device you only need these
modprobe btusb
sudo systemctl restart bluetooth.service
bluetoothctl
power on
agent on
default-agent
connect 45:DA:91:0D:14:69
exit

# If you have problems with the sound try to close pulseaudio and open again
# the close and open spotify or any media player
pulseaudio -k
pulseaudio --start



# Bose the volume is very low at maximum volume in Alsamixer.
pip install avrcp-volume
sudo -E avrcp-volume --install-service
systemctl --user start avrcp-volume.service
systemctl --user enable avrcp-volume.service
# Then open alsamixer and tap the PgUp key until the max,
# and keep tapping. It set the high volume in the speaker.
alsamixer

# How to see the volumen of the devices
pacmd list-sinks | grep -e "index:" -e "name:" -e "base volume:" -e "volume:"
VOLUME="+5%"
INDEX=$(pactl list short sinks | grep "bluez_sink" | awk '{ print $1 }' | head -n1)
echo "INDEX: ${INDEX}"
# Repeat this command to increase or decrease the volume.
# Needs to rebase the max volume to set the volume of the speaker or headset to 127.
pactl set-sink-volume "${INDEX}" "${VOLUME}"
pacmd list-sinks | grep -e "name:" -e "index:" -e "base volume:" -e "volume:"
# The volume is increasing not the base volume wich is the Alsamixer
# volume: front-left: 32768 /  50% / -18.06 dB,   front-right: 32768 /  50% / -18.06 dB balance 0.00
# base volume: 65536 / 100% / 0.00 dB
```
