### ISSUE TITLE
Installing on Fedora

### ISSUE THREAD

**Issue by matteioo** [airvzxf/bose-connect-app-linux#9]
Hi, do you know how to install your project on Fedora? I can't connect my Bose QuietComport headset with my laptop and I hope your project solves this issue. Unfortunately I have no experience with linux and therefore I can't figure it out on how to install your project on my newly setup Fedora notebook.

Cheers!

**Comment by airvzxf** [comment]
Unfortunately, I was interested in this project, but ultimately, it becomes easier to enable “party mode” manually. The creator of this project has also quoted that he has no interest in investing time:

> Denton-L commented on Sep 1, 2019
> 
> Hi, I would be interested in supporting it but I haven't had any time or interest recently in reverse-engineering and implementing it.
> 
> If you would like to implement support, you could use an Android phone with "Enable Bluetooth HCI snoop log" enabled from the Developer options. Enable and disable Music Share and then dump the logs into Wireshark and try to see if you can find the packets that do that action. Then the code should be straightforward enough to modify to add this option in.
> 
> Hope this helps!

However, there is a duo of developers who forked their project, just like me, but they have invested time in improving the code, currently it even compiles on Windows. I recommend that you install their version and in case it doesn't work on Fedora, add an issue to them.

https://github.com/zaddach/based-connect

I'll try two things, one of this is taking again this project, and add some test for Fedora. The second option, if I fail, I will archive this project.

**Comment by nicolaromano** [comment]
I could install this fine on Fedora 39.

You will need to install bluez-libs-devel for it to work (equivalent to libbluetooth-dev ) . Also, be sure to have cmake installed.

`sudo dnf -y install bluez-libs-devel`

Otherwise, the rest of the instructions apply to Fedora as well

**Comment by airvzxf** [comment]
It looks like the @nicolaromano solution should be work. Otherwise, please comment here.
